### ISSUE TITLE
X-Status-Reason should be x-status-reason

### ISSUE THREAD

**Issue by jurnbewise** [espocrm/php-espo-api-client#1]
In src/Client.php on line 227

`$errorMessage = $responseHeaders['X-Status-Reason'] ?? '';`

should be changd to:

`$errorMessage = $responseHeaders['x-status-reason'] ?? '';`

**Comment by yurikuzn** [comment]
No, it should not.

**Comment by yurikuzn** [comment]
Tested, it worked. Your webserver might be lower case header names.

It's too little input and no arguments, just a statement what we should do.

Maybe we would need to add a normalization, but definitely not what you suggested, as it would be a break.

**Comment by jurnbewise** [comment]
Agree, however I think a client should not be depending on the setting of the webserver. So in that case you could consider making all response header keys lowercase:

array_change_key_case($responseHeaders, CASE_LOWER);

**Comment by yurikuzn** [comment]
The client is very simple, we don't have parsed response headers (maybe will add in future). It's only the status-reason as far as I understand.

**Comment by yurikuzn** [comment]
For obtaining headers, I'd suggest using some additional lib (e.g. Guzzle). The response is available in the exception.

**Comment by jurnbewise** [comment]
last try :-)

```
$errorMessage = $responseHeaders['X-Status-Reason'] ?? '';
 throw new ResponseError($response, **$errorMessage**, $responseCode ?? 0);

```

So the code below will never work for php code used in webservers with lowercase headers:

...
```
catch ( ResponseError $e ) {
   $response = $e->getResponse();
  $message = ' Message ' . $e->getMessage() . PHP_EOL;
  ...
```

I think we had more discussion time then the time it should have taken to change it :-). But if you do not want to change it, fine with me.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/php-espo-api-client/commit/962ce6227ec47f3ec0c3a9ca2cbf6c794cb789fb

**Comment by yurikuzn** [comment]
New version is already in packagist.

**Comment by jurnbewise** [comment]
Just tested it, works as expected. Thanks a lot
